version: "3.3"

volumes:
  mysql_db_volume:
    driver: local

networks:
  Hillel_study:
    driver: bridge

services:
  app:
    build:
      context: docker/php
    restart: always
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    networks:
      - Hillel_study
  mysql_db:
    image: "mysql:8"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "mysql_db_volume:/var/lib/mysql"
    networks:
      - Hillel_study
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - Hillel_study
